### PR TITLE
Latest documentation and tutorial changes

### PR DESCRIPTION
**Pull request by lvotapka**
This updates the ReadTheDocs documentation and tutorial content by including some SERCA tutorials as well as bootstrapping tutorials and sample scripts. A number of Jupyter notebooks have also been included as well.

### CODE REVIEW

**Comment by marcushock** [comment]
Approving commit.

**Review by marcushock — APPROVED** [review]
Approved

**Review by marcushock — APPROVED** [review]
Ok, third time is the trick. Finally reviewed and approved all the files.

**Comment by lvotapka** [comment]
Thank you sir!

**Comment by lvotapka** [comment]
Hmm... it still isn't letting me merge these changes, even with your review. We probably need to ask @amstokely to review and approve these, and probably give one or both of us write access. How about it, @amstokely ?

**Review by amstokely — APPROVED** [review]

**Pull request merged**
